import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Calendar from '../components/Calendar'

export default function Home() {
    return (
    <>
      <Head>
        <title>BarkPlayLove</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Calendar />
      </main>

    </>
  );
}
